### ISSUE TITLE
FE: Recommended courses controller

### ISSUE THREAD

**Issue by mbbderobles** [2015firstcmsc100/galadhrim#191]
module name: galadhrimApp

$scope.recommendedCourses - should contain list of all recommended courses of a student
$scope.newRecommendedCourse - contains the new recommended course record to be added
$scope.editRecommendedCourse - contains the updated recommended course

$scope.addRecommendedCourse - function that calls to service to add new recommended course
$scope.editRecommendedCourse - function that calls to service to edit recommended course
$scope.deleteRecommendedCourse - function that confirms if the user is sure to delete the record, then calls to service to delete recommended course

**Comment by DeborahAbad** [comment]
Okay na po.
