### ISSUE TITLE
WS: Retrieve schedule of a student

### ISSUE THREAD

**Issue by kepbautista** [2015firstcmsc100/galadhrim#201]
Add a Web service endpoint for getting the details of all the 'ENLISTED' or 'RESERVED' slots of an existing student

GET
/api/ocm/schedule/:id
id - student number of the student

@query (optional) page - the position of the records in relation to how data are sorted
@query (optional) size - the number of records in a page

OK, 200
Returns an object containing the following:
page
size
data - array of slot records

Client error, 4xx
Returns an error containing the error message

**Comment by jdtdelrio** [comment]
Added Retrieve schedule of student
