### ISSUE TITLE
WS: Retrieve employees

### ISSUE THREAD

**Issue by kepbautista** [2015firstcmsc100/galadhrim#29]
Add a Web service endpoint for retrieving multiple employee records

GET
/api/employees
@query (optional) page - the position of the records in relation to how data are sorted
@query (optional) size - the number of records in a page

OK, 200
Returns an object containing the following:
* page
* size
* data - array of employee  records

Client error, 4xx
Returns an error record containing the error message

**Comment by mightybulacs** [comment]
* the endpoint doesn't guarantee that only those records with _recStatus equal to "Active" will be returned.
* the err object may contain server-side error; the endpoint assumed that it is client-side error hence returned a 4xx level status code
