### ISSUE TITLE
WS: Retrieve student records

### ISSUE THREAD

**Issue by kepbautista** [2015firstcmsc100/galadhrim#31]
Add a Web service endpoint for retrieving multiple student records

GET
/api/students
@query (optional) page - the position of the records in relation to how data are sorted
@query (optional) size - the number of records in a page

OK, 200
Returns an object containing the following:
* page
* size
* data - array of student records

Client error, 4xx
Returns an error record containing the error message

**Comment by emmanuelconstantino19** [comment]
add description for role and unitLevel
