### ISSUE TITLE
WS: Create course (subject)

### ISSUE THREAD

**Issue by mbbderobles** [2015firstcmsc100/galadhrim#37]
Add a Web service endpoint for adding a new course record.

POST
/api/courses
@param code - shorthand of the name of the course
@param name - name of the course
@param (optional) units - number of units of the course
@param (optional) semesterOffered - semester/s the course is offered
@param (optional) unitId - unit id of the course

OK, 200
Returns the newly created course record

Client error, 4xx
Returns an error recrod containing the error message

**Comment by mightybulacs** [comment]
* the endpoint does not guarantee that only valid values are accepted; e.g., passing a string as units, passing an invalid semester, and many others
* it will throw an error if there are no units, semesterOffered, and unitId
