### ISSUE TITLE
WS: Retrieve course (subject)

### ISSUE THREAD

**Issue by kepbautista** [2015firstcmsc100/galadhrim#39]
Add a Web service endpoint for displaying the course record

GET
/api/courses/:id

OK, 200
Returns the course record that matches the specified id

Client error, 4xx
Returns an error record containing the error message

**Comment by richardpitargue** [comment]
Finished this task. (see this commit: https://github.com/2015firstcmsc100/galadhrim/commit/e3d58cb5f0e9d3dfcc6bdb0281773d51dced47cd)

**Comment by richardpitargue** [comment]
See this commit for relevant updates for this task: https://github.com/2015firstcmsc100/galadhrim/commit/4b3038eeb3fcdcffc719e38071796d5160cecdae
