### ISSUE TITLE
WS: Retrieve courses (subjects)

### ISSUE THREAD

**Issue by kepbautista** [2015firstcmsc100/galadhrim#40]
Add a Web service endpoint for retrieving multiple course records

GET
/api/courses
@query (optional) page - the position of the records in relation to how data are sorted
@query (optional) size - the number of records in a page

OK, 200
Returns an object containing the following:
* page
* size
* data - array of course records

Client error, 4xx
Returns an error record containing the error message

**Comment by mightybulacs** [comment]
* Only courses with _recStatus equal to Active should be returned
