### ISSUE TITLE
WS: Retrieve announcements

### ISSUE THREAD

**Issue by mbbderobles** [2015firstcmsc100/galadhrim#62]
Add a Web service endpoint for retrieving multiple announcement records

GET
/api/announcements
@query (optional) page - the position of the records in relation to how data are sorted
@query (optional) size - the number of records in a page

OK, 200
Returns an object containing the following:
* page
* size
* data - array of announcement records

Client error, 4xx
Returns an error record containing the error message

**Comment by aadevera** [comment]
@mightybulacs @mbbderobles apparently someone already made my task
