### ISSUE TITLE
WS: Login

### ISSUE THREAD

**Issue by mightybulacs** [2015firstcmsc100/galadhrim#80]
Add a Web service endpoint for login.

POST
/api/login/

Check from the user record if the username with the given password exists:
@params username
@params password

If the username with the given password exists, add user to _login record: 

@params userId - user id of the user
@params sessionToken - (autogenerated) call getRandomString from galadhrim/lib/utils.js
@params ipAddress - can be found from request
@params expiration - 5 hours after login time

**Comment by keanpaderes** [comment]
Finished the web service endpoint. See my latest commit.
